name: New Library Request
description: Request new library to add to ArvanCloud library.
title: "New Library"
labels: ["➕ New Library"]
body:
- type: markdown
  attributes:
    value: |
      Enter your desired library information in the form below.

- type: input
  id: name
  attributes:
    label: "Library Name:"
    description: "Enter library name."
    placeholder: "vue"
  validations:
    required: true
    
- type: input
  id: address
  attributes:
    label: "Address:"
    description: "Library's source address."
    placeholder: "https://www.npmjs.com/package/vue or https://www.github.com/vuejs/vue"
  validations:
    required: true
